version: "3"

services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: viiv-synapse
    restart: unless-stopped
    ports:
      - "127.0.0.1:8008:8008"
    volumes:
      - ./synapse:/data
    environment:
      - SYNAPSE_SERVER_NAME=viiv.local
      - SYNAPSE_REPORT_STATS=no

  mautrix-meta:
    image: dock.mau.dev/mautrix/meta:latest
    container_name: viiv-mautrix-meta
    restart: unless-stopped
    ports:
      - "127.0.0.1:8009:29319"
    volumes:
      - ./mautrix:/data
    depends_on:
      - synapse
